//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.23 at 06:04:07 AM CEST 
//


package es.bsc.compss.types.resources.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourcesNIOAdaptorProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourcesNIOAdaptorProperties"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MinPort" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="MaxPort" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SpawnerPort" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="RemoteExecutionCommand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourcesNIOAdaptorProperties", propOrder = {
    "minPort",
    "maxPort",
    "spawnerPort",
    "remoteExecutionCommand"
})
public class ResourcesNIOAdaptorProperties {

    @XmlElement(name = "MinPort")
    protected int minPort;
    @XmlElement(name = "MaxPort")
    protected int maxPort;
    @XmlElement(name = "SpawnerPort")
    protected Integer spawnerPort;
    @XmlElement(name = "RemoteExecutionCommand")
    protected String remoteExecutionCommand;

    /**
     * Gets the value of the minPort property.
     * 
     */
    public int getMinPort() {
        return minPort;
    }

    /**
     * Sets the value of the minPort property.
     * 
     */
    public void setMinPort(int value) {
        this.minPort = value;
    }

    /**
     * Gets the value of the maxPort property.
     * 
     */
    public int getMaxPort() {
        return maxPort;
    }

    /**
     * Sets the value of the maxPort property.
     * 
     */
    public void setMaxPort(int value) {
        this.maxPort = value;
    }

    /**
     * Gets the value of the spawnerPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSpawnerPort() {
        return spawnerPort;
    }

    /**
     * Sets the value of the spawnerPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSpawnerPort(Integer value) {
        this.spawnerPort = value;
    }

    /**
     * Gets the value of the remoteExecutionCommand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteExecutionCommand() {
        return remoteExecutionCommand;
    }

    /**
     * Sets the value of the remoteExecutionCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteExecutionCommand(String value) {
        this.remoteExecutionCommand = value;
    }

}
