//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.23 at 06:04:05 AM CEST 
//


package es.bsc.compss.types.project.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StorageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StorageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Bandwidth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StorageType", propOrder = {
    "sizeOrTypeOrBandwidth"
})
public class StorageType {

    @XmlElements({
        @XmlElement(name = "Size", type = Float.class),
        @XmlElement(name = "Type", type = String.class),
        @XmlElement(name = "Bandwidth", type = Integer.class)
    })
    protected List<Serializable> sizeOrTypeOrBandwidth;

    /**
     * Gets the value of the sizeOrTypeOrBandwidth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sizeOrTypeOrBandwidth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSizeOrTypeOrBandwidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Float }
     * {@link String }
     * {@link Integer }
     * 
     * 
     */
    public List<Serializable> getSizeOrTypeOrBandwidth() {
        if (sizeOrTypeOrBandwidth == null) {
            sizeOrTypeOrBandwidth = new ArrayList<Serializable>();
        }
        return this.sizeOrTypeOrBandwidth;
    }

}
